apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: zerotier-{{ .Values.zerotier_config.zerotier_network_name }}-bridge
  namespace: {{ .Release.Namespace }}
  labels:
    network: {{ .Values.zerotier_config.zerotier_network_name }}
    service: {{ .Values.zerotier_config.zerotier_label_service }}
    environment: {{ .Values.environment }}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  selector:
    matchLabels:
      service: {{ .Values.zerotier_config.zerotier_label_service }}
  template:
    metadata:
      labels:
        network: {{ .Values.zerotier_config.zerotier_network_name }}
        service: {{ .Values.zerotier_config.zerotier_label_service }}
        environment: {{ .Values.environment }}
    spec:
      serviceAccountName: {{ include "kubernetes-zerotier-bridge.serviceAccountName" . }}
      hostNetwork: true
      containers:
      - name: zerotier-{{ .Values.zerotier_config.zerotier_network_name }}-bridge
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: CONSUL
            value: $(HOST_IP):8500
          - name: NETWORK_ID
            valueFrom:
              configMapKeyRef:
                name: zerotier-{{ .Values.environment }}-{{ .Release.Name }}
                key: NETWORK-ID
          - name: ZTAUTHTOKEN
            valueFrom:
              configMapKeyRef:
                name: zerotier-{{ .Values.environment }}-{{ .Release.Name }}
                key: ZTAUTHTOKEN
          - name: AUTOJOIN
            valueFrom:
              configMapKeyRef:
                name: zerotier-{{ .Values.environment }}-{{ .Release.Name }}
                key: AUTOJOIN
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN", "NET_RAW","SYS_ADMIN"]
        volumeMounts:
        - name: dev-net-tun
          mountPath: /dev/net/tun
        - name: ztdata
          mountPath: /var/lib/zerotier-one/
      volumes:
      - name: dev-net-tun
        hostPath:
          path: /dev/net/tun
      - name: ztdata
        hostPath:
          path: /var/lib/zerotier-one/
          type: DirectoryOrCreate
